repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        files: ^backend/
        args: [--fix]
      - id: ruff-format
        files: ^backend/

  - repo: local
    hooks:
      - id: frontend-format
        name: format(prettier)
        entry: bash -c "cd frontend && pnpm run format"
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|json|html|md|mdx)$
      - id: frontend-lint
        name: frontend-lint(eslint)
        entry: bash -c "cd frontend && pnpm run lint"
        language: system
        files: ^frontend/src/.*\.(js|jsx|ts|tsx)$
